on: 
  push:
    branches:
      - development
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: 166.62.28.83
        username: devcorbettsafari@corbettsafari.net
        password: 0P^e[JhJqBkG
        timeout_minutes : 1
        max_attempts : 3
